language: python
python:
  - '3.5'
  - '3.6'
cache: pip

services:
  - xvfb

install:
  - pip install -e .
branches:
  only:
    - master

script:
  - pytest tests
  # Run a few integration tests here - make sure they don't fail.
  - strainchoosr -t tests/tree_files/tree.nwk -n 4 6 8 10
