language: python
python:
  - '3.5'
  - '3.6'
cache: pip

services:
  - xvfb

env:
  - QT_QPA_PLATFORM=offscreen

install:
  - pip install -e .
branches:
  only:
    - master

script:
  - pytest tests
  # Run a few integration tests here - make sure they don't fail.
  # Normal strainchoosr run
  - strainchoosr -t tests/tree_files/tree.nwk -n 4 6 8 10
  # Specify starting strains
  - strainchoosr -t tests/tree_files/tree.nwk -n 4 6 8 --starting_strains 2018-SEQ-1295.fasta 2017-MER-0763.fasta 2017-SEQ-0094.fasta
  # Tree weights TODO
