language: python
python:
  - '3.5'
  - '3.6'
cache: pip

install:
  - pip install -e .
branches:
  only:
    - master

script:
  - pytest tests
  - strainchoosr -t tests/tree_files/tree.nwk -n 4 6 8 10
