language: python
python:
  - '3.5'
  - '3.6'
cache: pip

services:
  - xvfb

env:
  - QT_QPA_PLATFORM=offscreen  # Need this in order to have the Qt powered tree drawing work.

install:
  - pip install -e .
branches:
  only:
    - master

before_script:
  - pip install codecov

script:
  - coverage run setup.py pytest

after_success:
  - codecov
