language: python
python:
  - '3.5'
  - '3.6'
cache: pip

env:
  - QT_QPA_PLATFORM=offscreen  # Need this in order to have the Qt powered tree drawing work.

install:
  - pip install -e .
branches:
  only:
    - master

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - pip install codecov

script:
#  - coverage run setup.py pytest
  - pytest -vvvvv

#after_success:
#  - codecov
